/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Enable dbus support? */
#undef CONFIG_DBUS

/* Is json-c required? */
#define CONFIG_JSONC

/* Is libkeyutils available? */
#undef CONFIG_KEYUTILS

/* Is liburing available? */
#undef CONFIG_LIBURING

/* Is OpenSSL/LibreSSL available? */
#define CONFIG_OPENSSL

#define GIT_VERSION ""

/* Building for big-endian */
#define HAVE_BIG_ENDIAN 0

/* Is bswap_64 available? */
#define HAVE_BSWAP_64 0

/* Is __builtin_types_compatible_p available? */
#define HAVE_BUILTIN_TYPES_COMPATIBLE_P 1

/* Is byteswap.h include-able? */
#define HAVE_BYTESWAP_H 0

/* Is isblank() available? */
#define HAVE_ISBLANK 1

/* Is dlsym function present */
#undef HAVE_LIBC_DLSYM

/* Is linux/mctp.h include-able? */
#define HAVE_LINUX_MCTP_H 0

/* Building for little-endian */
#define HAVE_LITTLE_ENDIAN 1

/* Is network address and service translation available */
#undef HAVE_NETDB

/* Can we use a statement as an expression? */
#define HAVE_STATEMENT_EXPR 1

/* Is typeof available? */
#define HAVE_TYPEOF 1

#define PROJECT_VERSION "1.15"

#define SYSCONFDIR "/usr/local/etc"

#define fallthrough __attribute__((__fallthrough__))

