/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Is json-c available? */
#define CONFIG_JSONC

/* Is json-c at least 0.14? */
#define CONFIG_JSONC_14

#define DEFAULT_PDC_ENABLED 0

#define GIT_VERSION ""

/* Is compiler warning about unused static line function? */
#define HAVE_ATTRIBUTE_UNUSED 0

/* Building for big-endian */
#define HAVE_BIG_ENDIAN 0

/* Is bswap_64 available? */
#define HAVE_BSWAP_64 0

/* Is __builtin_types_compatible_p available? */
#define HAVE_BUILTIN_TYPES_COMPATIBLE_P 1

/* Is byteswap.h include-able? */
#define HAVE_BYTESWAP_H 0

/* Is isblank() available? */
#define HAVE_ISBLANK 1

/* Does struct opal_key have a key_type field? */
#define HAVE_KEY_TYPE 0

/* Building for little-endian */
#define HAVE_LITTLE_ENDIAN 1

/* Is linux/sed-opal.h include-able? */
#define HAVE_SED_OPAL 0

/* Is sys/random.h(getrandom) include-able? */
#define HAVE_SYS_RANDOM 0

/* Does struct tm have a tm_gmtoff field? */
#undef HAVE_TM_GMTOFF

/* Is typeof available? */
#define HAVE_TYPEOF 1

#define NVME_VERSION "2.15"

#define RUNDIR "/usr/local/run"

#define SYSCONFDIR "/usr/local/etc"

#define fallthrough __attribute__((__fallthrough__))

